image: docker
services:
  - docker:dind

variables:
  NODE_APP_API_URL: $NODE_APP_API_URL

stages:
  - lint
  - test
  - deploy

lint:
  tags:
    - cognate
  stage: lint
  only:
    refs:
      - main
      - develop
  image: node:latest
  before_script:
    - echo "Install npm"
    - npm install
    - echo "Running linter"
  script:
    - npm run lint

test:
  tags:
    - cognate
  stage: test
  only:
    refs:
      - main
      - develop
  image: node:latest
  before_script:
    - echo "Install npm"
    - npm install
    - echo "Running tests"
  script:
    - echo "no tests written yet :("

deploy:
  tags:
    - cognate
    - main-deploy
  stage: deploy
  only:
    refs:
      - main
  environment: main
  before_script:
    - docker-compose version
    - echo NODE_APP_API_URL=$NODE_APP_API_URL >> .env
  script:
    - echo "Building Docker container"
    - docker-compose down
    - docker-compose up -d --build

deploy-dev:
  tags:
    - cognate
    - dev-deploy
  stage: deploy
  only:
    refs:
      - develop
  environment: develop
  before_script:
    - docker-compose version
    - echo NODE_APP_API_URL=$NODE_APP_API_URL >> .env
  script:
    - echo "Building Docker container"
    - docker-compose down
    - docker-compose up -d --build

